

tasks: 
  - name: Start the MongoDB database
    init: |
      docker compose build
      gp sync-done docker-build
    command: docker compose up mongo

  - name: Build and Run NodeGoat
    init: |
      npm install && npm run build
      gp sync-await docker-build # Wait for the above init to finish
    command: |
      gp ports await 27017
      npm run db:seed
      npm run start

ports: 
  - name: NodeGoat
    port: 4000
    onOpen: open-preview
  - name: MongoDB
    port: 27017
    onOpen: ignore

vscode:
  extensions:
    - amvanbaren.runme

