image: 
  file: .gitpod.Dockerfile

tasks: 
  - name: MongoDB database
    init: |
      docker compose build
    command: docker compose up mongo

  - name: NodeGoat application
    init: |
      npm install
    command: |
      open README.md 
      gp ports await 27017
      npm run db:seed
      npm run start

ports: 
  - name: NodeGoat
    port: 4000
    onOpen: open-preview
  - name: MongoDB
    port: 27017
    onOpen: ignore

vscode:
  extensions:
    - amvanbaren.runme

